exchanges:
  - binance
  - bybit
  - kraken
  - okx
  - kucoin
  - gateio
  - huobi
  - bitget
  - mexc

symbols:
  - BTC/USDT
  - ETH/USDT

interval: 5
min_spread: 0.2
top: 5

mode: orderbook
orderbook_depth: 10
orderbook_amount: 1000.0

stats_window: 20

log_level: INFO
log_file: logs/app.log