[project]
name = "cryptospreadtracker"
version = "0.1.0"
description = ""
authors = [
    {name = "null-route-dev",email = "null-route-dev@protonmail.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "python-dotenv (>=1.2.2,<2.0.0)",
    "colorama (>=0.4.6,<0.5.0)",
    "websockets (>=17.0.1,<18.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
package-mode = false